// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCR_M9FdbE74fE_PFJjhlE1p3cABq3RYw',
    appId: '1:786174971598:web:116ceb85583eae2a2f4a9f',
    messagingSenderId: '786174971598',
    projectId: 'xovibe-d2b67',
    authDomain: 'xovibe-d2b67.firebaseapp.com',
    storageBucket: 'xovibe-d2b67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7HfBfINZRwDhLTBMcsGw4IeqCB1Y_qI0',
    appId: '1:786174971598:android:f4d6712194b23dbd2f4a9f',
    messagingSenderId: '786174971598',
    projectId: 'xovibe-d2b67',
    storageBucket: 'xovibe-d2b67.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCR_M9FdbE74fE_PFJjhlE1p3cABq3RYw',
    appId: '1:786174971598:web:abf3a990e6e428fb2f4a9f',
    messagingSenderId: '786174971598',
    projectId: 'xovibe-d2b67',
    authDomain: 'xovibe-d2b67.firebaseapp.com',
    storageBucket: 'xovibe-d2b67.firebasestorage.app',
  );
}
